# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lbl_caminho = QtWidgets.QLabel(parent=self.frame)
        self.lbl_caminho.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_caminho.setObjectName("lbl_caminho")
        self.verticalLayout_3.addWidget(self.lbl_caminho)
        self.btn_abrir = QtWidgets.QPushButton(parent=self.frame)
        self.btn_abrir.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_abrir.setObjectName("btn_abrir")
        self.verticalLayout_3.addWidget(self.btn_abrir)
        self.listWidget = QtWidgets.QListWidget(parent=self.frame)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.btn_relatorio = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_relatorio.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_relatorio.setObjectName("btn_relatorio")
        self.verticalLayout_2.addWidget(self.btn_relatorio)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bolsa Família"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Caminho do arquivo:</p></body></html>"))
        self.lbl_caminho.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_abrir.setText(_translate("MainWindow", "Abrir pasta de arquivo"))
        self.groupBox.setTitle(_translate("MainWindow", "Relatórios"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Acompanhados"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Não acompanhados"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Profissional</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Todos"))
        self.btn_relatorio.setText(_translate("MainWindow", "Gerar relatório"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
